version: '3'
services:
  zookeeper0:
    image: "cloudurable/zookeeper-image:0.3"
    restart: always
    ports:
     - "2181:2181"
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=1
  zookeeper1:
    image: "cloudurable/zookeeper-image:0.3"
    restart: always
    ports:
     - "2182:2181"
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=2
  zookeeper2:
    image: "cloudurable/zookeeper-image:0.3"
    restart: always
    ports:
     - "2183:2181"
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=3
  kafka0:
    image: "cloudurable/kafka-image"
    restart: always
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
     - "9092:9092"
    links:
     - zookeeper0
     - zookeeper1
     - zookeeper2
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
     - KAFKA_BROKER_ID=1
     - KAFKA_CLUSTER_MODE=auto
     - KAFKA_LISTENERS=PLAINTEXT://kafka0:9092
     - KAFKA_DEFAULT_REPLICATION=1
#  kafka1:
#    image: "cloudurable/kafka-image"
#    restart: always
#    depends_on:
#      - zookeeper0
#      - zookeeper1
#      - zookeeper2
#    ports:
#     - "9093:9092"
#    links:
#     - zookeeper0
#     - zookeeper1
#     - zookeeper2
#    environment:
#     - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
#     - KAFKA_BROKER_ID=2
#     - KAFKA_CLUSTER_MODE=auto
#     - KAFKA_LISTENERS=PLAINTEXT://kafka1:9092
#     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093
#     - KAFKA_DEFAULT_REPLICATION=1
#  kafka2:
#    image: "cloudurable/kafka-image"
#    restart: always
#    depends_on:
#      - zookeeper0
#      - zookeeper1
#      - zookeeper2
#    ports:
#     - "9094:9092"
#    links:
#     - zookeeper0
#     - zookeeper1
#     - zookeeper2
#    environment:
#     - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
#     - KAFKA_BROKER_ID=3
#     - KAFKA_CLUSTER_MODE=auto
#     - KAFKA_LISTENERS=PLAINTEXT://kafka2:9092
#     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094
#     - KAFKA_DEFAULT_REPLICATION=1
